Repository flare-foundation/developer-hub, pull requests merged in 2025-03, with the labels that each got.

#587 feat(ui): add a progress bar in the onboarding doc
  docs/hackathon/0-onboarding.mdx
  docs/hackathon/1-cookbook.mdx
  src/components/ConfidentialVMBuilder.tsx
  src/components/hackathon/OnboardingChecklist.tsx
  src/css/custom.css
Labels: enhancement

#590 docs(fassets): add IAssetManager reference and update operational parameters page
  docs/fassets/6-operational-parameters.mdx
  docs/fassets/reference/IAssetManager.mdx
Labels: option.do-not-merge

#607 feat: add script for feed table generator
  automations/custom_feeds.json
  docs/ftso/2-feeds.mdx
  src/components/DataTables/CustomFeeds.tsx
Labels: high priority
