Repository flare-foundation/developer-hub, pull requests merged in 2025-02, with the labels that each got.

#581 feat(docs): new hackathon page and enhancement of the onboarding
  docs/hackathon/0-onboarding.mdx
  docs/hackathon/1-VM-Setup.mdx
  sidebars.ts
  static/img/verifiable-ai-hackathon/access-granted.png
  static/img/verifiable-ai-hackathon/choose-template.png
  static/img/verifiable-ai-hackathon/create-key.png
  static/img/verifiable-ai-hackathon/gemini-key.png
Labels: option.do-not-merge

#586 feat(audit): add latest audit in february
  docs/support/audits.mdx
  static/pdf/audits/20250205-Coinspect-SmartContractAudit-Flare-FTSOv2CustomFeedsDiffReview-v240210.pdf
Labels: documentation

#588 feat(docs): refactor FAssets operational parameters page with dynamic component
  docs/fassets/6-operational-parameters.mdx
  src/components/FAssets/OperationalParameters.tsx
  src/components/FAssets/operational-parameters.ts
Labels: documentation

#591 feat(whitepapers): add support for whitepapers
  docs/support/audits.mdx
  docs/support/whitepapers.mdx
  docusaurus.config.ts
  src/components/WhitepapersGrid.tsx
  src/css/custom.css
  static/pdf/whitepapers/20191105-FlareConsensusProtocol.pdf
  static/pdf/whitepapers/20220722-HybridPostQuantumDigitalSignatureSchemeForTheEthereumVirtualMachine.pdf
  static/pdf/whitepapers/20221231-TheFlareNetworkAndFLRToken.pdf
  static/pdf/whitepapers/20230406-KrakenExchange-FTSOPriceComparison.pdf
  static/pdf/whitepapers/20230529-SongbirdBandUpdate-ImpactOfSTP02.pdf
  static/pdf/whitepapers/20240223-FlareTimeSeriesOracleV2.pdf
  static/pdf/whitepapers/20240224-FlareDataConnector.pdf
  static/pdf/whitepapers/20240225-ConsensusLearning.pdf
  static/pdf/whitepapers/remove_spaces.sh
Labels: documentation, enhancement
